kind = "web"
previewPath = "/"
title = "WFoods ComandaFácil"
version = "1.0.0"
id = "artifacts/wfoods"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 26233

[services.development]
run = "pnpm --filter @workspace/wfoods run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/wfoods", "run", "build" ]
publicDir = "artifacts/wfoods/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "26233"
BASE_PATH = "/"
